# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

G_update <- function(y, X, beta, mu, tau) {
    .Call('_LSBP_G_update', PACKAGE = 'LSBP', y, X, beta, mu, tau)
}

Expectation_step <- function(y, X, beta, mu, tau) {
    .Call('_LSBP_Expectation_step', PACKAGE = 'LSBP', y, X, beta, mu, tau)
}

Variational_step <- function(rho, linpred, residual, tau, ltau) {
    .Call('_LSBP_Variational_step', PACKAGE = 'LSBP', rho, linpred, residual, tau, ltau)
}

pred_mean <- function(X, beta, mu) {
    .Call('_LSBP_pred_mean', PACKAGE = 'LSBP', X, beta, mu)
}

pred_var <- function(X, beta, mu, tau) {
    .Call('_LSBP_pred_var', PACKAGE = 'LSBP', X, beta, mu, tau)
}

pred_cdf <- function(X, beta, mu, tau, threshold) {
    .Call('_LSBP_pred_cdf', PACKAGE = 'LSBP', X, beta, mu, tau, threshold)
}

predictive <- function(X, beta, mu, tau) {
    .Call('_LSBP_predictive', PACKAGE = 'LSBP', X, beta, mu, tau)
}

G_update_multi <- function(y, X1, X2, beta, gamma, tau) {
    .Call('_LSBP_G_update_multi', PACKAGE = 'LSBP', y, X1, X2, beta, gamma, tau)
}

Expectation_step_multi <- function(y, X1, X2, beta, gamma, tau) {
    .Call('_LSBP_Expectation_step_multi', PACKAGE = 'LSBP', y, X1, X2, beta, gamma, tau)
}

pred_mean_multi <- function(X1, X2, beta, gamma) {
    .Call('_LSBP_pred_mean_multi', PACKAGE = 'LSBP', X1, X2, beta, gamma)
}

pred_var_multi <- function(X1, X2, beta, gamma, tau) {
    .Call('_LSBP_pred_var_multi', PACKAGE = 'LSBP', X1, X2, beta, gamma, tau)
}

pred_cdf_multi <- function(X1, X2, beta, gamma, tau, threshold) {
    .Call('_LSBP_pred_cdf_multi', PACKAGE = 'LSBP', X1, X2, beta, gamma, tau, threshold)
}

predictive_multi <- function(X1, X2, beta, gamma, tau) {
    .Call('_LSBP_predictive_multi', PACKAGE = 'LSBP', X1, X2, beta, gamma, tau)
}

stick_breaking <- function(X, beta) {
    .Call('_LSBP_stick_breaking', PACKAGE = 'LSBP', X, beta)
}

LSBP_density_C <- function(y, X1, X2, beta, gamma, tau) {
    .Call('_LSBP_LSBP_density_C', PACKAGE = 'LSBP', y, X1, X2, beta, gamma, tau)
}

