# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

G_update <- function(y, X, beta, mu, tau) {
    .Call('DLSBP_G_update', PACKAGE = 'DLSBP', y, X, beta, mu, tau)
}

Expectation_step <- function(y, X, beta, mu, tau) {
    .Call('DLSBP_Expectation_step', PACKAGE = 'DLSBP', y, X, beta, mu, tau)
}

Variational_step <- function(rho, y, X, beta, mu, tau_tilde, tau, ltau) {
    .Call('DLSBP_Variational_step', PACKAGE = 'DLSBP', rho, y, X, beta, mu, tau_tilde, tau, ltau)
}

prediction <- function(X, beta, mu, tau) {
    .Call('DLSBP_prediction', PACKAGE = 'DLSBP', X, beta, mu, tau)
}

